### ISSUE TITLE
While creating domain with ucm

### ISSUE THREAD

**Issue by karunakarchil** [justinpaulthekkan/oracle-fmw-tooling#1]
/u01/app/oracle/wcchome/oracle_common/common/bin/wlst.sh create_domain_off.py -h /u01/app/oracle/wcchome/user_projects/domains/TEST_domain -c hostname:1521:orcl -m TEST --domain_name TEST_domain --db_password Welcome1 --nm_password Welcome1 --as_password Welcome1 wls ucm

Data Sources Auto Config
Error: getDatabaseDefaults() failed. Do dumpStack() to see details.
Error: runCmd() failed. Do dumpStack() to see details.
Problem invoking WLST - Traceback (innermost last):
  File "/u01/stage/WCC/kk/extend_domain_off.py", line 201, in ?
  File "/u01/stage/WCC/kk/extend_domain_off.py", line 173, in main
  File "/tmp/WLSTOfflineIni3166871218067095204.py", line 253, in getDatabaseDefaults
  File "/tmp/WLSTOfflineIni3166871218067095204.py", line 19, in command
Failed to build JDBC Connection object:
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2666)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:698)
        at sun.reflect.GeneratedMethodAccessor667.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: Got exception when auto configuring the schema component(s) with data obtained from shadow table:
Failed to build JDBC Connection object:

**Comment by karunakarchil** [comment]
My MW_HOME= /u01/app/oracle/wcchome

**Comment by freneticdisc** [comment]
Thank you for posting the issue.

Couple of things that I would like to ask:
1. Is the database up and running on hostname:1521:orcl?
2. Have you run the RCU to create the necessary schemas? With WebCenter 12c, to create a new domain you must have the ${PREFIX}_STB schema which stores the configuration. You also need the OPSS and the Audit schemas that gets selected once you select a product in RCU.
3. The getDatabaseDefaults() method really just connects to the ${PREFIX}_STB schema and gathers the information to update the settings for the datasources; so this error likely suggests that the schema does not exist or that the database is not running.

**Comment by karunakarchil** [comment]
Thanks a lot ..issue with ${PREFIX}_STB schema password. Now i am able to create domain.

**Comment by samitadtran** [comment]
Hi I don't see any such variable "${PREFIX}_STB" in my case, I built it via docker image, and have below file 
vagrant@ubuntu:/scratch$ cat oam-admin.env 
DOMAIN_NAME=us.oracle.com
ADMIN_USER=admin
ADMIN_PASSWORD=Admin@135
ADMIN_LISTEN_HOST=oamadmin
ADMIN_LISTEN_PORT=7001
CONNECTION_STRING=oamadmin.f5net:1521:orcl
RCUPREFIX=OAM01
DB_USER=sys
DB_PASSWORD=yj7bJTFGPIU=1
DB_SCHEMA_PASSWORD=Admin@135

Getting the following errors here
Configuring JDBC Templates ...
Configuring the Service Table DataSource...
fmwDatabase  jdbc:oracle:thin:@oamadmin.f5net:1521:orcl
Getting Database Defaults...
Error: getDatabaseDefaults() failed. Do dumpStack() to see details.
Error: runCmd() failed. Do dumpStack() to see details.
Problem invoking WLST - Traceback (innermost last):
  File "/u01/oracle/dockertools/create_domain.py", line 513, in ?
  File "/u01/oracle/dockertools/create_domain.py", line 124, in createOAMDomain
  File "/u01/oracle/dockertools/create_domain.py", line 328, in extendOamDomain
  File "/u01/oracle/dockertools/create_domain.py", line 259, in configureJDBCTemplates
  File "/tmp/WLSTOfflineIni6616673952125645598.py", line 267, in getDatabaseDefaults
  File "/tmp/WLSTOfflineIni6616673952125645598.py", line 19, in command
Failed to build JDBC Connection object: 
	at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
	at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:3085)
	at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:738)
	at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: Got exception when auto configuring the schema component(s) with data obtained from shadow table: 
Failed to build JDBC Connection object: 

Domain Creation Failed.. Please check the Domain Logs


I also created oracle DB via below files 
root@ubuntu:/scratch# cat env.txt 
DB_ID=InfraDB
DB_PDB=InfraPDB1
DB_DOMAIN=us.oracle.com
DB_BUNDLE=basic


And the two containers are being run by below comands
docker run -d -p 7001:7001 --name oamadmin --network=OamNET --env-file /scratch/oam-admin.env --volume /scratch/user_projects:/u01/oracle/user_projects oracle/oam:12.2.1.4.0
-----------------------------------------------------------------------------------
docker run -d --name InfraDB --network=OamNET -p 1521:1521 -p 5500:5500 --env-file env.txt -it --shm-size="8g" container-registry.oracle.com/database/enterprise:latest


Please help to identify the probelm
