### ISSUE TITLE
extend_domain_off.py no examples

### ISSUE THREAD

**Issue by karunakarchil** [justinpaulthekkan/oracle-fmw-tooling#5]
Hi,

extend_domain_off.py no examples..Its same command like create domain?

[-?] -h domain_home [-s shared_home] -c db_connect_string -m db_prefix [-w password_file] [--domain_name domain_name] [--nm_port nm_port] [--as_port adminserver_port] [--as_ssl_port adminserver_sslport] [--db_password db_datasource_passwd] [--nm_password nodemanager_passwd] [--as_password adminserver_password] wls

**Comment by karunakarchil** [comment]
Loading Required Templates.
        Oracle WSM Policy Manager version 12.2.1.0
Setting Domain Options.
Configuring feature ows.
Data Sources Auto Config
Writing Domain Configuration.
Error: runCmd() failed. Do dumpStack() to see details.
Problem invoking WLST - Traceback (innermost last):
  File "/ows_app/stage/kk/extend_domain_off.py", line 201, in ?
  File "/ows_app/stage/kk/extend_domain_off.py", line 177, in main
  File "/tmp/WLSTOfflineIni7368748867049764582.py", line 135, in updateDomain
  File "/tmp/WLSTOfflineIni7368748867049764582.py", line 19, in command
64254: Error occurred in "Artifacts Generation" phase execution
64254: Encountered error: 64038: The app-svc-name "wsm-pm" must have target.
64038: The app-svc-name "wsm-pm" must have target.
64038: Provide a valid target.
64254: Check log for more detail.

        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2666)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:698)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

https://docs.oracle.com/middleware/1221/wls/WLDTR/fmw_templates.htm#WLDTR497

In Json file added below entry.
"ows": {
        "version": "12.2.1.0",
        "template-name": "Oracle WSM Policy Manager"
    }

**Comment by freneticdisc** [comment]
You will need more information in the JSON file. There is already an entry for WSM in the JSON and it has to be modified to add information to set them up on separate managed servers:

"wsm": {
        "version": "12.2.1",
        "server-name": "WSM_server1",
        "server-name-prefix": "wsm_pm_",
        "server-port": 9010,
        "server-ssl-port": 9110,
        "cluster-name": "wsm_cluster1",
        "file-stores": [
            "mds-owsm"
        ],
        "comp_ids": [
            "MDS"
        ],
        "template-name": "Oracle WSM Policy Manager"
    },

After this change, you also need to update the extend_domain.py script to create the managed servers and I don't remember the template adding managed servers.

Justin

**Comment by karunakarchil** [comment]
Hi,
Thanks for the quick update.

Error:-

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Reading the Domain to gather information.
Loading the Domain for update.
Loading Required Templates.
        Oracle WSM Policy Manager version 12.2.1.0
Setting Domain Options.
Configuring feature ows.
        Updating Filestore mds-owsm
Problem invoking WLST - Traceback (innermost last):
  File "/ows_app/stage/kk/extend_domain_off.py", line 201, in ?
  File "/ows_app/stage/kk/extend_domain_off.py", line 124, in main
NameError: as_name
